ansible_host: 10.1.100.157
router_id: 172.16.2.1
bgp_global_asn: 65000
ecmp: True
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.152.1/30
    unit: 152
    mpls:
      state: False
      protocol: none
    routing_instance: CUST1
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.154.2/30
    unit: 154
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.155.2/30
    unit: 155
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.167.1/30
    unit: 167
    mpls:
      state: False
      protocol: none
    routing_instance: CUST1
  - name: lo0
    ipv4:
      - address: 172.16.2.1/32
    unit: 0
    mpls:
      state: True
      protocol: ldp

ospf_areas:
  - id: 0
    interfaces:
      - name: ge-0/0/0.152
        type: p2p
        passive: True
      - name: ge-0/0/0.154
        type: p2p
        passive: False
      - name: ge-0/0/0.155
        type: p2p
        passive: False
      - name: ge-0/0/0.167
        type: p2p
        passive: True
      - name: lo0.0
        type: loop
        passive: True

policies:
  - name: EXPORT-CUST1
    terms:
      - id: 1
        froms:
          - type: protocol
            data: bgp
        thens:
          - type: community
            type_action: add
            data: CUST1COMM
          - type: terminate
            terminating_action: accept
      - id: 2
        thens:
          - type: terminate
            terminating_action: reject
  - name: IMPORT-CUST1
    terms:
      - id: 1
        froms:
          - type: protocol
            data: bgp
          - type: community
            data: CUST1COMM
        thens:
          - type: terminate
            terminating_action: accept
      - id: 2
        thens:
          - type: terminate
            terminating_action: reject
communities:
  - name: CUST1COMM
    id: "target:65000:1"

provider_ibgp:
  group:
    name: SP-IBGP
    local_address: "{{ router_id }}"
    import_policy: IMPORT-CUST1
    export_policy: EXPORT-CUST1
    asn: 65000
    neighbors:
      - ip: 172.16.3.1
      - ip: 172.16.6.1
      - ip: 172.16.7.1

routing_instances:
  - name: CUST1
    rd: 172.16.2.1:1
    rt: target:65000:1
    bgp:
      group:
        name: cust1
        type: external
        neighbors:
          - asn: 65001
            ip: 10.254.152.2
          - asn: 65003
            ip: 10.254.167.2
