ansible_host: 10.1.100.157
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.152.1/30
    unit: 152
    mpls:
      state: False
      protocol: none
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.154.2/30
    unit: 154
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.155.2/30
    unit: 155
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.167.1/30
    unit: 167
    mpls:
      state: False
      protocol: none
  - name: lo0
    ipv4:
      - address: 172.16.2.1/32
    unit: 0
    mpls:
      state: True
      protocol: ldp

router_id: 172.16.2.1
ospf_areas:
  - id: 0
    interfaces:
      - name: ge-0/0/0.152
        type: p2p
        passive: True
      - name: ge-0/0/0.154
        type: p2p
        passive: False
      - name: ge-0/0/0.155
        type: p2p
        passive: False
      - name: ge-0/0/0.167
        type: p2p
        passive: True
      - name: lo0.0
        type: loop
        passive: True

ecmp: True
policies:
  - name: EXPORT-CUST1
    terms:
      - id: 1
        froms:
          - type: protocol
            data: bgp
        thens:
          - type: community
            type_action: add
            data: CUST1COMM
          - type: terminate
            terminating_action: accept
      - id: 2
        thens:
          - type: terminate
            terminating_action: reject
  - name: IMPORT-CUST1
    terms:
      - id: 1
        froms:
          - type: protocol
            data: bgp
          - type: community
            data: CUST1COMM
        thens:
          - type: terminate
            terminating_action: accept
      - id: 2
        thens:
          - type: terminate
            terminating_action: reject
communities:
  - name: CUST1COMM
    id: "target:65000:1"
