ansible_host: 10.1.100.161
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.154.1/30
    unit: 154
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.156.1/30
    unit: 156
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.160.1/30
    unit: 160
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.161.1/30
    unit: 161
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.164.1/30
    unit: 164
  - name: lo0
    ipv4:
      - address: 172.16.4.1/32
    unit: 0

router_id: 172.16.4.1
ospf_areas:
  - id: 0
    interfaces:
      - name: ge-0/0/0.154
        type: p2p
        passive: False
      - name: ge-0/0/0.156
        type: p2p
        passive: False
      - name: ge-0/0/0.160
        type: p2p
        passive: False
      - name: ge-0/0/0.161
        type: p2p
        passive: False
      - name: ge-0/0/0.164
        type: p2p
        passive: False
      - name: lo0.0
        type: loop
        passive: True
