ansible_host: 10.1.100.163
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.155.1/30
    unit: 155
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.157.1/30
    unit: 157
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.160.2/30
    unit: 160
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.162.1/30
    unit: 162
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.163.1/30
    unit: 163
    mpls:
      state: True
      protocol: ldp
  - name: lo0
    ipv4:
      - address: 172.16.5.1/32
    unit: 0
    mpls:
      state: True
      protocol: ldp

router_id: 172.16.5.1

ospf_areas:
  - id: 0
    interfaces:
      - name: ge-0/0/0.155
        type: p2p
        passive: False
      - name: ge-0/0/0.157
        type: p2p
        passive: False
      - name: ge-0/0/0.160
        type: p2p
        passive: False
      - name: ge-0/0/0.162
        type: p2p
        passive: False
      - name: ge-0/0/0.163
        type: p2p
        passive: False
      - name: lo0.0
        type: loop
        passive: True
