ansible_host: 10.1.100.163
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.155.1/30
    unit: 155
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.157.1/30
    unit: 157
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.160.2/30
    unit: 160
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.162.1/30
    unit: 162
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.163.1/30
    unit: 163
  - name: lo0
    ipv4:
      - address: 172.16.5.1/32
    unit: 0
