ansible_host: 10.1.100.165
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.162.2/30
    unit: 162
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.164.1/30
    unit: 164
    mpls:
      state: True
      protocol: ldp
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.165.1/30
    unit: 165
    mpls:
      state: False
      protocol: none
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.168.1/30
    unit: 168
    mpls:
      state: False
      protocol: none
  - name: lo0
    ipv4:
      - address: 172.16.6.1/32
    unit: 0
    mpls:
      state: True
      protocol: ldp

router_id: 172.16.6.1
ospf_areas:
  - id: 0
    interfaces:
      - name: ge-0/0/0.162
        type: p2p
        passive: False
      - name: ge-0/0/0.164
        type: p2p
        passive: False
      - name: ge-0/0/0.165
        type: p2p
        passive: False
      - name: ge-0/0/0.168
        type: p2p
        passive: True
      - name: lo0.0
        type: loop
        passive: True
