ansible_host: 10.1.100.169
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to net_lab_int vSwitch
    enabled: True
  - name: ge-0/0/1
    description: Physical Interface to vmx8_clients vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.165.2/30
    unit: 165
  - name: ge-0/0/0
    ipv4:
      - address: 10.254.166.2/30
    unit: 166
  - name: ge-0/0/1
    ipv4:
      - address: 10.254.170.1/24
    unit: 0
  - name: lo0
    ipv4:
      - address: 172.16.8.1/32
    unit: 0

ecmp: True
policies:
  - name: bgp-export
    terms:
      - id: 1
        froms:
          - type: protocol
            data: direct
        thens:
          - type: terminate
            terminating_action: accept
